### PR TITLE
link to docs added, badge improved

### LINKED ISSUE #374: "Learn More" for all document types
### Which API Provider are you using?

AWS Bedrock

### Which Model are you using?

NA

### What happened?

NA

### Steps to reproduce

1.Open a solution
2.Info icon must be present in the document listing (next to the title or anywhere suitable)
3.Click "Learn More" to redirect to specifai.io's relevant documentation

### Relevant API REQUEST output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chidam-presidio**
### Description

fixes #374 

### Type of Change

-   [x] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [ ] ✨ New feature (non-breaking change which adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] 📚 Documentation update

### Pre-flight Checklist

-   [x] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [ ] I have reviewed [contributor guidelines](https://github.com/presidio-oss/specif-ai/blob/main/CONTRIBUTING.md)

### Screenshots
Screenshot 2025-08-08 at 5 39 28 PM

### CODE REVIEW

File: ui/src/app/pages/test-cases/test-case-list/test-case-list.component.ts [hunk 1]
```diff
@@ -104,8 +106,10 @@ export class TestCaseListComponent implements OnInit, OnDestroy {
   logger = inject(NGXLogger);
   store = inject(Store);
   searchService = inject(SearchService);
+  electronService = inject(ElectronService);
   requirementFile: any = [];
   testCases: ITestCase[] = [];
+  docUrl = SPECIFAI_REQ_DOCS['TC'];
```
Comment (krithika7402) [inline ui/src/app/pages/test-cases/test-case-list/test-case-list.component.ts:112]: same here (let's use REQUIREMENT_TYPE.TC instead)

File: ui/src/app/constants/specifai-req-types-docs.constants.ts
Comment (krithika7402) [inline ui/src/app/constants/specifai-req-types-docs.constants.ts:1]: can we move the contents of this file to ui/src/app/constants/app.constants.ts

File: ui/src/app/pages/test-cases/test-case-home/test-case-home.component.html [hunk 2]
```diff
@@ -8,6 +8,11 @@
           class="text-lg font-bold text-secondary-800 truncate max-w-full pr-8"
         >
           Test Cases
+            <ng-icon
+              name="heroInformationCircle"
+              (click)="electronService.openExternalUrl(docUrl)"
```
Comment (krithika7402) [inline ui/src/app/pages/test-cases/test-case-home/test-case-home.component.html:13]: 1. alignment is a little off here, can this be looked into? 
2. when user stories are empty there's a weird line appearing due to no count, can we take a look? (it is supposed/used to display 0 as the count)

image

File: ui/src/app/pages/test-cases/test-case-list/test-case-list.component.html [hunk 3]
```diff
@@ -14,6 +14,11 @@
 
         <div class="flex items-center">
           <h2 class="text-md font-semibold text-secondary-600">Test Cases</h2>
+            <ng-icon
+              name="heroInformationCircle"
```
Comment (krithika7402) [inline ui/src/app/pages/test-cases/test-case-list/test-case-list.component.html:18]: when test cases are empty there's a weird line appearing due to no count, can we take a look? (it is supposed/used to display 0 as the count)
image

**Review by krithika7402 — APPROVED** [review]
LGTM

**Review by krithika7402 — APPROVED** [review]
